[package]
name = "ferret_os"
version = "0.1.0"
authors = ["Gianmarco Donnici <gianmarco.donnici@gmail.com>"]
edition = "2018"

# Disable unwinding (needed to have a free-standing exec)
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
